name: MineResetLite
version: ${project.version}
api-version: 1.15
main: com.koletar.jj.mineresetlite.MineResetLite
author: jjkoletar
description: A lightweight solution for Mine management.
depend: [WorldEdit]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.